### PR TITLE
Revert "add test"

### LINKED ISSUE #253: Build failure on master (from 1dd5ec9 onwards)
#### Issue Description

```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/huitseeker/DL4J/DataVec/datavec-api/src/main/java/org/datavec/api/transform/stringreduce/StringReducer.java:[283,56] cannot find symbol
  symbol:   class ConditionalReduction
  location: class org.datavec.api.transform.stringreduce.StringReducer.Builder
[ERROR] /home/huitseeker/DL4J/DataVec/datavec-api/src/main/java/org/datavec/api/transform/stringreduce/StringReducer.java:[283,17] cannot find symbol
  symbol: variable conditionalReductions
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] DataVec ............................................ SUCCESS [  1.718 s]
[INFO] datavec-api ........................................ FAILURE [  5.304 s]
[INFO] datavec-data ....................................... SKIPPED
[INFO] datavec-data-audio ................................. SKIPPED
[INFO] datavec-nd4j-common ................................ SKIPPED
[INFO] datavec-data-image ................................. SKIPPED
[INFO] datavec-data-codec ................................. SKIPPED
[INFO] datavec-data-nlp ................................... SKIPPED
[INFO] datavec-geo ........................................ SKIPPED
[INFO] datavec-hadoop ..................................... SKIPPED
[INFO] datavec-spark_2.11 ................................. SKIPPED
[INFO] DataVec Camel Component ............................ SKIPPED
[INFO] datavec-dataframe .................................. SKIPPED
[INFO] datavec-local ...................................... SKIPPED
[INFO] datavec-spark-inference-server ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.209 s
[INFO] Finished at: 2017-05-07T12:39:44-04:00
[INFO] Final Memory: 33M/701M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project datavec-api: Compilation failure: Compilation failure: 
[ERROR] /home/huitseeker/DL4J/DataVec/datavec-api/src/main/java/org/datavec/api/transform/stringreduce/StringReducer.java:[283,56] cannot find symbol
[ERROR]   symbol:   class ConditionalReduction
[ERROR]   location: class org.datavec.api.transform.stringreduce.StringReducer.Builder
[ERROR] /home/huitseeker/DL4J/DataVec/datavec-api/src/main/java/org/datavec/api/transform/stringreduce/StringReducer.java:[283,17] cannot find symbol
[ERROR]   symbol: variable conditionalReductions
[ERROR] -> [Help 1]
[ERROR] 
```

Full log : https://gist.github.com/001d0d4ea4fd20d217cc5a7dec2318c2
#### Version Information

Bisection shows 1dd5ec9 is the commit that introduces the failure

### PR DESCRIPTION
**Pull request by huitseeker**
This reverts commit 1dd5ec98f9657e70e3e87a88502846c8c3c09e51.
Fixes #253

### CODE REVIEW

**Comment by agibsonccc** [comment]
Closed in favor of #255
